# name of the software
name: FreeCast 

# list of additional links on the right of the top menu
headerLinks:

# list if additional links on the footer
footerLinks:
  - title: © 2016 FreeCast
    url: https://freecast.online/
  
# header
header:
  color1: "#ffffff"
  color2: "#ffffff"
  trianglify: false

# google analytics
analytics:
  account: UA-38808585-2
  domain: freecast.online

exclude: ['bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
